server:
  port: 8080
spring:
#  config:
#    activate:
#      on-profile: dev
  application:
    name: pickle-ball_dev
  datasource:
    url: jdbc:mysql://localhost:3306/pickle_ball_dev?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver